import { notFound } from "next/navigation";
import { DISCLAIMER } from "@/lib/constants";
import { StatusBadge } from "@/components/status";
import { getWorkspace } from "@/lib/api/client";

export const dynamic="force-dynamic";
export default async function DossierPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const p=await getWorkspace(id).catch(()=>null);if(!p)notFound();return <main className="shell" style={{maxWidth:1100}}>
  <section className="page-head"><div><div className="eyebrow">Afdrukbaar dossieroverzicht</div><h1 style={{marginTop:10}}>{p.name}</h1><p>{p.client} · {p.reference} · beoordeling gegenereerd op {new Date().toLocaleDateString("nl-NL")}</p></div><button className="button button-primary no-print" onClick={undefined}>Gebruik browsermenu: Afdrukken / Bewaar als PDF</button></section>
  <section className="panel panel-pad" style={{marginBottom:20}}><h2>Projectgegevens</h2><dl className="grid-2" style={{marginTop:18}}><Meta label="Opdrachtgever" value={p.client}/><Meta label="Referentie" value={p.reference}/><Meta label="Product" value={`${p.product} ${p.productVersion}`}/><Meta label="Verantwoordelijke" value={p.owner}/><Meta label="Uiterste inleverdatum" value={formatDate(p.dueDate)}/><Meta label="Aantal bewijsstukken" value={String(p.evidenceDocuments.length)}/></dl></section>
  <div className="notice warning" style={{marginBottom:20}}>{DISCLAIMER}</div>
  <div className="stack">{p.requirements.map(r=>{const a=r.assessments[0],m=a?.evidenceMatchId?r.matches.find(x=>x.id===a.evidenceMatchId):r.matches[0];return <article className="panel panel-pad" key={r.id} style={{breakInside:"avoid"}}><div style={{display:"flex",justifyContent:"space-between",gap:20}}><div><div className="eyebrow">{r.number} · {r.category} · {r.priority}</div><h2 style={{marginTop:7}}>{r.title}</h2></div><StatusBadge status={r.status}/></div><p style={{lineHeight:1.6}}>{r.originalText}</p><p className="source-quote">{r.sourceFragment}</p><p className="muted" style={{fontSize:11}}>Bron: {r.sourceDocument?.name||"Handmatig"} · {r.sourceLocation}</p><div className="grid-2" style={{marginTop:18}}><div><h3>Menselijke beoordeling</h3><p>{a?.draftAnswer||"Geen conceptantwoord vastgelegd."}</p><p className="muted" style={{fontSize:12}}>{a?.notes||"Geen opmerkingen."}</p><Meta label="Beoordeeld door" value={a?`${a.assessedBy}, ${formatDate(a.assessedAt)}`:"Nog niet beoordeeld"}/></div><div><h3>Gekoppeld bewijs</h3>{m?<><p><strong>{m.evidenceDocument.title}</strong> <span className="score">{m.score}% voorstel</span></p><p className="source-quote">{m.fragment||"Geen letterlijk fragment beschikbaar."}</p><p className="muted" style={{fontSize:11}}>{m.evidenceDocument.fileName} · {m.sourceLocation}</p>{m.warnings&&<p className="notice warning">{m.warnings}</p>}</>:<p className="notice danger">Openstaande hiaat: geen bewijs gekoppeld.</p>}</div></div></article>})}</div>
  <div className="notice" style={{marginTop:22}}>{DISCLAIMER}</div>
  <script dangerouslySetInnerHTML={{__html:`document.querySelector('.no-print')?.addEventListener('click',()=>window.print())`}}/>
  </main>}
function Meta({label,value}:{label:string;value:string}){return <div><dt className="muted" style={{fontSize:11}}>{label}</dt><dd style={{margin:"4px 0 0",fontWeight:650}}>{value||"—"}</dd></div>}
function formatDate(value:string|null|undefined){return value?new Date(value.length===10?`${value}T12:00:00`:value).toLocaleDateString("nl-NL"):"Niet vastgelegd"}
