(() => {
  const requirements = [
    { id: 'E-001', title: 'Encryptie van gegevens', category: 'Informatiebeveiliging', source: 'Programma van eisen · p. 12', evidence: 'Architectuurbeschrijving', score: 94, status: 'voldoende', fragment: 'Gegevens worden versleuteld tijdens transport en opslag.' },
    { id: 'E-002', title: 'Toegangsbeheer en logging', category: 'Informatiebeveiliging', source: 'Securityvragenlijst · p. 4', evidence: 'Informatiebeveiligingsbeleid', score: 82, status: 'gedeeltelijk', fragment: 'Toegang is rolgebaseerd; beheeracties worden vastgelegd.' },
    { id: 'E-003', title: 'Bewaartermijnen persoonsgegevens', category: 'Privacy', source: 'Privacybijlage · §3.2', evidence: '—', score: 18, status: 'ontbrekend', fragment: 'Geen passend fragment gevonden.' },
    { id: 'E-004', title: 'Subverwerkers inzichtelijk', category: 'Privacy', source: 'Privacybijlage · §5', evidence: 'Subprocessorregister', score: 91, status: 'voorstel', fragment: 'Het register noemt hosting- en analysepartners met land en doel.' },
    { id: 'E-005', title: 'Melding van incidenten', category: 'Continuïteit', source: 'Contractvoorwaarde · art. 8', evidence: 'Incidentprocedure', score: 88, status: 'voldoende', fragment: 'Incidenten worden binnen 24 uur gemeld aan de contactpersoon.' },
    { id: 'E-006', title: 'Menselijke tussenkomst bij AI', category: 'AI en algoritmen', source: 'AI-vragenlijst · vraag 11', evidence: 'Model card', score: 74, status: 'gedeeltelijk', fragment: 'Een medewerker kan een voorgestelde planning controleren en aanpassen.' },
    { id: 'E-007', title: 'Wijzigingen aan het AI-model', category: 'AI en algoritmen', source: 'AI-vragenlijst · vraag 16', evidence: '—', score: 12, status: 'ontbrekend', fragment: 'Geen passend fragment gevonden.' },
    { id: 'E-008', title: 'Continuïteit en gegevensopslag EER', category: 'Continuïteit', source: 'Programma van eisen · p. 28', evidence: 'Continuïteitsplan', score: 86, status: 'voorstel', fragment: 'Back-ups en primaire opslag staan in datacenters binnen de EER.' }
  ];
  const evidence = ['Informatiebeveiligingsbeleid', 'Subprocessorregister', 'Architectuurbeschrijving', 'Incidentprocedure', 'Model card', 'Continuïteitsplan', 'Pentestsamenvatting (verlopen)'];
  const content = document.querySelector('#demo-content');
  if (!content) return;
  const saved = JSON.parse(localStorage.getItem('ipc-pages-demo') || '{}');
  requirements.forEach((item) => { item.status = saved[item.id] || item.status; });
  let activeTab = 'overview';
  let selectedId = requirements[0].id;
  const statusLabel = { voldoende: 'Voldoende onderbouwd', gedeeltelijk: 'Gedeeltelijk onderbouwd', voorstel: 'Mogelijk passend', ontbrekend: 'Ontbrekend bewijs' };
  const statusClass = (status) => `status status-${status}`;
  const getProgress = () => Math.round((requirements.filter((r) => r.status === 'voldoende' || r.status === 'gedeeltelijk').length / requirements.length) * 100);
  const row = (r) => `<button class="req-row" data-requirement="${r.id}"><span class="req-id">${r.id}</span><span><strong>${r.title}</strong><small>${r.category} · ${r.source}</small></span><span class="req-evidence">${r.evidence}</span><span class="score">${r.score}%</span><span class="${statusClass(r.status)}">${statusLabel[r.status]}</span></button>`;
  const showDetail = (id) => { const r = requirements.find((x) => x.id === id) || requirements[0]; selectedId = r.id; const target = document.querySelector('#req-detail'); if (!target) return; target.innerHTML = `<div><span class="eyebrow">${r.id} · bronfragment</span><h3>${r.title}</h3><blockquote>“${r.fragment}”</blockquote><small>${r.source}</small></div><div><label for="status-${r.id}">Menselijke beoordeling</label><select id="status-${r.id}" data-status="${r.id}">${Object.entries(statusLabel).map(([key, label]) => `<option value="${key}" ${key === r.status ? 'selected' : ''}>${label}</option>`).join('')}</select><p class="detail-warning">Voorstel: ${r.evidence}. Controleer scope, productversie en geldigheid voordat je beslist.</p><button class="button button-dark" data-save="${r.id}" type="button">Beoordeling opslaan</button></div>`; bind(); };
  const render = () => {
    if (activeTab === 'overview') content.innerHTML = `<div class="demo-overview"><div class="overview-lead"><span class="eyebrow">Voortgang op menselijke beoordeling</span><strong>${getProgress()}%</strong><p>Automatische voorstellen tellen niet mee. Alleen opgeslagen beoordelingen veranderen de voortgang.</p><div class="progress"><i style="width:${getProgress()}%"></i></div></div><div class="overview-cards"><div><span>Openstaande hiaten</span><strong>${requirements.filter((r) => r.status === 'ontbrekend').length}</strong><small>direct opvolgen</small></div><div><span>Bronnen gekoppeld</span><strong>7</strong><small>fragmenten zichtbaar</small></div><div><span>Documenten</span><strong>7</strong><small>waarvan 1 verlopen</small></div></div><div class="overview-next"><div><span class="eyebrow">Volgende logische actie</span><h3>Vraag een eigenaar om E-003 en E-007 aan te vullen.</h3><p>De matcher heeft geen sterk bronfragment gevonden. Leg een eigenaar en deadline vast voordat je exporteert.</p></div><button class="button button-outline" data-tab="requirements" type="button">Bekijk eisen</button></div></div>`;
    if (activeTab === 'requirements' || activeTab === 'matrix') content.innerHTML = `<div class="demo-table-head"><div><span class="eyebrow">${activeTab === 'matrix' ? 'Eisen-bewijsmatrix' : 'Concept-eisen'}</span><h3>${requirements.length} eisen uit de bron</h3></div><button class="button button-outline" id="export-csv" type="button">Exporteer CSV</button></div><div class="req-table">${requirements.map(row).join('')}</div><div class="req-detail" id="req-detail"></div>`;
    if (activeTab === 'evidence') content.innerHTML = `<div class="demo-table-head"><div><span class="eyebrow">Bewijsbibliotheek</span><h3>7 bewijsstukken beschikbaar</h3></div><span class="expiry-warning">1 document verlopen</span></div><div class="evidence-list">${evidence.map((name, i) => `<div><span class="file-icon">${i === 6 ? '!' : '·'}</span><span><strong>${name}</strong><small>${i === 6 ? 'Pentest · verlopen op 14-08-2026' : 'PDF · bijgewerkt 08-09-2026'}</small></span><span class="${i === 6 ? 'status status-ontbrekend' : 'status status-voldoende'}">${i === 6 ? 'Verlopen' : 'Beschikbaar'}</span></div>`).join('')}</div>`;
    bind();
    if (activeTab === 'requirements' || activeTab === 'matrix') showDetail(selectedId);
  };
  const bind = () => {
    document.querySelectorAll('[data-requirement]').forEach((el) => el.addEventListener('click', () => showDetail(el.dataset.requirement)));
    document.querySelectorAll('[data-tab]').forEach((el) => el.addEventListener('click', () => { activeTab = el.dataset.tab; document.querySelectorAll('.demo-tab').forEach((tab) => { const on = tab.dataset.tab === activeTab; tab.classList.toggle('is-active', on); tab.setAttribute('aria-selected', on); }); render(); }));
    document.querySelector('#export-csv')?.addEventListener('click', () => { const csv = ['Nummer,Titel,Categorie,Status,Bewijs,Score', ...requirements.map((r) => [r.id, r.title, r.category, statusLabel[r.status], r.evidence, r.score].map((v) => `"${String(v).replaceAll('"', '""')}"`).join(','))].join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'ipc-matrix-demo.csv'; link.click(); URL.revokeObjectURL(url); });
    document.querySelectorAll('[data-save]').forEach((el) => el.addEventListener('click', () => { const id = el.dataset.save; const value = document.querySelector(`[data-status="${id}"]`).value; const next = JSON.parse(localStorage.getItem('ipc-pages-demo') || '{}'); next[id] = value; localStorage.setItem('ipc-pages-demo', JSON.stringify(next)); requirements.find((r) => r.id === id).status = value; render(); }));
  };
  document.querySelector('#reset-demo')?.addEventListener('click', () => { localStorage.removeItem('ipc-pages-demo'); window.location.reload(); });
  render();
})();
