import Link from "next/link";
import { notFound } from "next/navigation";
import { CATEGORIES, DISCLAIMER, EVIDENCE_TYPES, SOURCE_TYPES, STATUSES } from "@/lib/constants";
import { addRequirementAction, deleteRequirementAction, extractRequirementsAction, generateMatchesAction, mergeRequirementsAction, saveAssessmentAction, updateRequirementAction, uploadEvidenceAction, uploadSourceAction } from "@/app/actions";
import { ConfirmButton, SubmitButton } from "@/components/submit-button";
import { ExpiryBadge, StatusBadge } from "@/components/status";
import { expiryState } from "@/lib/matching";
import { getWorkspace, type WorkspaceResponse } from "@/lib/api/client";

export const dynamic = "force-dynamic";
const tabs = [["overzicht","Overzicht"],["documenten","Aanbestedingsdocumenten"],["eisen","Eisen"],["bewijs","Bewijsbibliotheek"],["matrix","Eisen-bewijsmatrix"],["acties","Openstaande acties"],["audit","Auditlog"],["export","Export"]];

export default async function ProjectPage({ params, searchParams }: { params: Promise<{id:string}>; searchParams: Promise<Record<string,string|undefined>> }) {
  const { id } = await params; const query = await searchParams; const tab = query.tab || "overzicht";
  const project = await getWorkspace(id).catch(() => null);
  if(!project) notFound();
  return <main className="shell">
    <section className="page-head"><div><Link href="/dossiers" className="eyebrow">Dossiers / {project.reference || "zonder referentie"}</Link><h1 style={{marginTop:10}}>{project.name}</h1><p>{project.client} · {project.product} {project.productVersion} · verantwoordelijke {project.owner || "nog niet toegewezen"}</p></div><div style={{textAlign:"right"}}><span className="muted" style={{fontSize:12}}>Uiterste inleverdatum</span><div className="mono" style={{fontSize:18,fontWeight:700,color:"var(--navy)",marginTop:5}}>{formatDate(project.dueDate)}</div></div></section>
    <nav className="tabs no-print" aria-label="Projectonderdelen">{tabs.map(([key,label])=><Link key={key} href={`/projecten/${id}?tab=${key}`} className={`tab ${tab===key?"tab-active":""}`}>{label}</Link>)}</nav>
    {tab === "overzicht" && <Overview project={project}/>} 
    {tab === "documenten" && <Sources project={project}/>} 
    {tab === "eisen" && <Requirements project={project}/>} 
    {tab === "bewijs" && <Evidence project={project}/>} 
    {tab === "matrix" && <Matrix project={project} query={query}/>} 
    {tab === "acties" && <Tasks project={project}/>} 
    {tab === "audit" && <Audit project={project}/>} 
    {tab === "export" && <Export project={project}/>} 
  </main>;
}

type FullProject = WorkspaceResponse;
function formatDate(value:string|null|undefined){return value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString("nl-NL"):"Niet vastgelegd"}
function formatDateTime(value:string){return new Date(value).toLocaleString("nl-NL")}

function Overview({project}:{project:FullProject}) {
  const total=project.requirements.length, sufficient=project.requirements.filter(r=>r.status==="voldoende onderbouwd").length, partial=project.requirements.filter(r=>r.status==="gedeeltelijk onderbouwd").length, missing=project.requirements.filter(r=>["ontbrekend bewijs","onvoldoende onderbouwd"].includes(r.status)).length, unreviewed=project.requirements.filter(r=>["niet beoordeeld","mogelijk passend"].includes(r.status)).length;
  const humanReviewed=total-unreviewed, progress=total?Math.round(humanReviewed/total*100):0, expired=project.evidenceDocuments.filter(e=>expiryState(e.expiresAt)==="verlopen").length, soon=project.evidenceDocuments.filter(e=>expiryState(e.expiresAt)==="verloopt binnenkort").length;
  return <div className="stack">
    <div className="stats"><div className="stat"><div className="stat-value mono">{progress}%</div><div className="stat-label">Menselijk beoordeeld</div><div className="progress"><span style={{width:`${progress}%`}}/></div></div><Stat n={total} label="Totaal eisen"/><Stat n={sufficient} label="Voldoende"/><Stat n={partial} label="Gedeeltelijk"/><Stat n={missing} label="Ontbrekend"/></div>
    <div className="grid-wide"><section className="panel panel-pad"><div className="section-head"><div><h2>Stand van het dossier</h2><p className="muted" style={{fontSize:13}}>Alleen vastgelegde menselijke beoordelingen tellen mee.</p></div><Link className="button button-primary button-small" href={`/projecten/${project.id}?tab=matrix`}>Open matrix</Link></div><div className="grid-2"><Summary label="Niet beoordeeld" value={unreviewed} tone="neutral"/><Summary label="Verlopen bewijs" value={expired} tone="bad"/><Summary label="Verloopt binnen 30 dagen" value={soon} tone="partial"/><Summary label="Openstaande acties" value={project.tasks.filter(t=>t.status==="open").length} tone="proposal"/></div></section>
      <aside className="panel panel-pad"><h2>Dossiercontext</h2><dl style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"14px 10px",fontSize:12,marginTop:20}}><Meta label="Opdrachtgever" value={project.client}/><Meta label="Referentie" value={project.reference}/><Meta label="Product" value={project.product}/><Meta label="Versie" value={project.productVersion}/><Meta label="Bronnen" value={String(project.sourceDocuments.length)}/><Meta label="Bewijsstukken" value={String(project.evidenceDocuments.length)}/></dl></aside></div>
    <div className="notice">{DISCLAIMER}</div>
  </div>;
}
function Stat({n,label}:{n:number;label:string}){return <div className="stat"><div className="stat-value mono">{n}</div><div className="stat-label">{label}</div></div>}
function Summary({label,value,tone}:{label:string;value:number;tone:string}){return <div style={{borderTop:"1px solid var(--line)",paddingTop:13}}><StatusBadge status={tone==="good"?"voldoende onderbouwd":tone==="partial"?"gedeeltelijk onderbouwd":tone==="bad"?"ontbrekend bewijs":tone==="proposal"?"mogelijk passend":"niet beoordeeld"}/><div className="mono" style={{fontSize:24,fontWeight:700,marginTop:10}}>{value}</div><div className="muted" style={{fontSize:11}}>{label}</div></div>}
function Meta({label,value}:{label:string;value:string}){return <div><dt className="muted">{label}</dt><dd style={{margin:"4px 0 0",fontWeight:650}}>{value||"—"}</dd></div>}

function Sources({project}:{project:FullProject}) { return <div className="grid-wide"><section className="panel"><div className="panel-pad section-head"><div><h2>Aanbestedingsdocumenten</h2><p className="muted" style={{fontSize:13}}>PDF, DOCX of TXT · maximaal 10 MB</p></div></div>{project.sourceDocuments.length===0?<Empty title="Nog geen brondocumenten" text="Upload een uitvraag om lokaal concept-eisen te herkennen."/>:<div>{project.sourceDocuments.map(doc=><div className="list-row" key={doc.id}><div><h3>{doc.name}</h3><p className="muted" style={{fontSize:11,margin:"5px 0 0"}}>{doc.type} · {formatDateTime(doc.uploadedAt)} · {doc.extractedText.length.toLocaleString("nl-NL")} tekens</p></div><span className="badge status-neutral">tekst beschikbaar</span><form action={extractRequirementsAction.bind(null,project.id,doc.id)}><SubmitButton className="button button-secondary button-small" pending="Extraheren…">Eisen extraheren</SubmitButton></form></div>)}</div>}</section>
    <aside className="panel panel-pad"><h2>Document toevoegen</h2><form action={uploadSourceAction.bind(null,project.id)} className="form-stack" style={{marginTop:20}}><Select name="type" label="Classificatie" options={SOURCE_TYPES}/><FileField/><SubmitButton pending="Uploaden en uitlezen…">Document uploaden</SubmitButton></form><div className="notice" style={{marginTop:20}}>Bestanden worden buiten de publieke webmap bewaard en zijn alleen via dit dossier benaderbaar.</div></aside></div> }

function Requirements({project}:{project:FullProject}) { return <div className="stack"><div className="grid-wide"><section className="panel"><div className="panel-pad section-head"><div><h2>Eisen</h2><p className="muted" style={{fontSize:13}}>{project.requirements.length} traceerbare eisen</p></div></div>{project.requirements.length===0?<Empty title="Nog geen eisen" text="Extraheer eisen uit een document of voeg er handmatig één toe."/>:<div>{project.requirements.map(req=><details key={req.id}><summary className="list-row"><div><div className="mono muted" style={{fontSize:10}}>{req.number} · {req.origin}</div><h3 style={{marginTop:4}}>{req.title}</h3></div><span className="badge status-neutral">{req.category}</span><StatusBadge status={req.status}/></summary><div className="detail"><div className="split-detail"><div><p className="source-quote">{req.sourceFragment}</p><p className="muted" style={{fontSize:11}}>Bron: {req.sourceDocument?.name||"Handmatig"} · {req.sourceLocation}</p></div><form action={updateRequirementAction.bind(null,project.id,req.id)} className="form-stack"><Field name="title" label="Korte titel" defaultValue={req.title}/><div className="field"><label htmlFor={`text-${req.id}`}>Eistekst</label><textarea id={`text-${req.id}`} name="originalText" defaultValue={req.originalText}/><small>De oorspronkelijke bronpassage blijft afzonderlijk bewaard.</small></div><div className="grid-2"><Select name="category" label="Categorie" options={CATEGORIES} defaultValue={req.category}/><Select name="priority" label="Type" options={["verplicht","wens"]} defaultValue={req.priority}/></div><label className="checkline"><input type="checkbox" name="notApplicable" defaultChecked={req.notApplicable}/> Niet van toepassing</label><div style={{display:"flex",gap:8}}><SubmitButton className="button button-primary button-small" pending="Opslaan…">Wijzigingen opslaan</SubmitButton></div></form></div><form action={deleteRequirementAction.bind(null,project.id,req.id)} style={{marginTop:18}}><ConfirmButton>Eis verwijderen</ConfirmButton></form></div></details>)}</div>}</section>
      <aside className="stack"><section className="panel panel-pad"><h2>Handmatig toevoegen</h2><form action={addRequirementAction.bind(null,project.id)} className="form-stack" style={{marginTop:18}}><Field name="title" label="Korte titel"/><div className="field"><label htmlFor="manual-text">Eistekst *</label><textarea id="manual-text" name="originalText" required/></div><Select name="category" label="Categorie" options={CATEGORIES}/><Select name="priority" label="Type" options={["verplicht","wens"]}/><SubmitButton>Eis toevoegen</SubmitButton></form></section>
      {project.requirements.length>1&&<section className="panel panel-pad"><h2>Eisen samenvoegen</h2><p className="muted" style={{fontSize:12}}>De tweede eis wordt opgenomen in de eerste, inclusief bronfragment.</p><form action={mergeRequirementsAction.bind(null,project.id)} className="form-stack"><Select name="primaryId" label="Behouden eis" options={project.requirements.map(r=>r.id)} optionLabels={Object.fromEntries(project.requirements.map(r=>[r.id,`${r.number} — ${r.title}`]))}/><Select name="secondaryId" label="Samenvoegen en verwijderen" options={project.requirements.map(r=>r.id)} optionLabels={Object.fromEntries(project.requirements.map(r=>[r.id,`${r.number} — ${r.title}`]))}/><SubmitButton className="button button-secondary">Samenvoegen</SubmitButton></form></section>}</aside></div></div> }

function Evidence({project}:{project:FullProject}) { return <div className="grid-wide"><section className="panel"><div className="panel-pad section-head"><div><h2>Bewijsbibliotheek</h2><p className="muted" style={{fontSize:13}}>{project.evidenceDocuments.length} bewijsstukken binnen dit dossier</p></div></div>{project.evidenceDocuments.length===0?<Empty title="Nog geen bewijsstukken" text="Voeg beleidsstukken, rapporten of technische documentatie toe."/>:<div>{project.evidenceDocuments.map(doc=>{const state=expiryState(doc.expiresAt);return <details key={doc.id}><summary className="list-row"><div><h3>{doc.title}</h3><p className="muted" style={{fontSize:11,margin:"5px 0 0"}}>{doc.documentType} · {doc.organization||"Entiteit niet ingevuld"} · {doc.confidentiality}</p></div><ExpiryBadge state={state}/><div className="muted" style={{fontSize:11}}>{doc.product||"Geen productscope"} {doc.productVersion}<br/>{doc.environment||"Geen omgeving"}</div></summary><div className="detail"><div className="grid-2"><div><h3>Beschrijving</h3><p className="muted">{doc.description||"Geen beschrijving."}</p><Meta label="Eigenaar" value={doc.owner}/><Meta label="Tags" value={doc.tags}/></div><div><h3>Geldigheid en scope</h3><p className="muted" style={{fontSize:12}}>Afgifte: {doc.issuedAt?formatDate(doc.issuedAt):"—"}<br/>Vervaldatum: {doc.expiresAt?formatDate(doc.expiresAt):"—"}<br/>Bestand: {doc.fileName}</p></div></div></div></details>})}</div>}</section>
    <aside className="panel panel-pad"><h2>Bewijsstuk registreren</h2><form action={uploadEvidenceAction.bind(null,project.id)} className="form-stack" style={{marginTop:18}}><Field name="title" label="Titel"/><Select name="documentType" label="Documenttype" options={EVIDENCE_TYPES}/><div className="field"><label htmlFor="description">Korte omschrijving</label><textarea id="description" name="description"/></div><Field name="organization" label="Organisatie / juridische entiteit" defaultValue="Planwijzer Systemen B.V."/><div className="grid-2"><Field name="product" label="Product of dienst" defaultValue={project.product}/><Field name="productVersion" label="Productversie" defaultValue={project.productVersion}/></div><div className="grid-2"><Field name="environment" label="Omgeving" placeholder="productie"/><Field name="owner" label="Eigenaar"/></div><div className="grid-2"><Field name="issuedAt" label="Datum van afgifte" type="date"/><Field name="expiresAt" label="Vervaldatum" type="date"/></div><Select name="confidentiality" label="Vertrouwelijkheid" options={["openbaar","intern","vertrouwelijk","strikt vertrouwelijk"]}/><Field name="tags" label="Tags" placeholder="encryptie, beheer, ISO"/><FileField/><SubmitButton pending="Uploaden en registreren…">Bewijsstuk toevoegen</SubmitButton></form></aside></div> }

function Matrix({project,query}:{project:FullProject;query:Record<string,string|undefined>}) {
  const filtered=project.requirements.filter(r=>(!query.category||r.category===query.category)&&(!query.status||r.status===query.status)&&(!query.priority||r.priority===query.priority)&&(!query.document||r.sourceDocumentId===query.document)&&(!query.owner||r.assessments[0]?.owner===query.owner)&&(!query.missing||["ontbrekend bewijs","onvoldoende onderbouwd"].includes(r.status)));
  const owners=[...new Set(project.requirements.map(r=>r.assessments[0]?.owner).filter(Boolean))] as string[];
  return <div className="stack"><div className="notice">{DISCLAIMER}</div><div className="section-head no-print"><div><h2>Eisen-bewijsmatrix</h2><p className="muted" style={{fontSize:13}}>Automatische voorstellen worden pas definitief na uw beoordeling.</p></div><form action={generateMatchesAction.bind(null,project.id)}><SubmitButton pending="Voorstellen berekenen…">Bewijsvoorstellen genereren</SubmitButton></form></div>
  <form method="get" className="panel panel-pad no-print"><input type="hidden" name="tab" value="matrix"/><div style={{display:"grid",gridTemplateColumns:"repeat(6,minmax(120px,1fr))",gap:10}}><SelectCompact name="category" label="Categorie" options={CATEGORIES} value={query.category}/><SelectCompact name="status" label="Status" options={STATUSES} value={query.status}/><SelectCompact name="owner" label="Verantwoordelijke" options={owners} value={query.owner}/><SelectCompact name="priority" label="Verplicht/wens" options={["verplicht","wens"]} value={query.priority}/><SelectCompact name="document" label="Document" options={project.sourceDocuments.map(d=>d.id)} optionLabels={Object.fromEntries(project.sourceDocuments.map(d=>[d.id,d.name]))} value={query.document}/><label className="checkline" style={{alignSelf:"end",minHeight:42}}><input name="missing" value="1" type="checkbox" defaultChecked={query.missing==="1"}/> Alleen hiaten</label></div><div style={{marginTop:12,display:"flex",gap:8}}><button className="button button-secondary button-small">Filters toepassen</button><Link href={`/projecten/${project.id}?tab=matrix`} className="button button-small">Wissen</Link></div></form>
  <section className="panel table-wrap"><table><thead><tr><th>Nummer</th><th>Korte eis</th><th>Categorie</th><th>Bron</th><th>Status</th><th>Beste voorstel</th><th>Score</th><th>Eigenaar</th><th>Actie</th></tr></thead><tbody>{filtered.map(req=>{const best=req.matches[0],assessment=req.assessments[0];return <tr key={req.id}><td className="mono">{req.number}</td><td style={{maxWidth:260,fontWeight:650}}>{req.title}</td><td>{req.category}</td><td>{req.sourceDocument?.name||"Handmatig"}<div className="muted" style={{fontSize:10}}>{req.sourceLocation}</div></td><td><StatusBadge status={req.status}/></td><td>{best?.evidenceDocument.title||<span className="muted">Geen voorstel</span>}</td><td>{best?<span className="score">{best.score}%</span>:"—"}</td><td>{assessment?.owner||"—"}</td><td><details><summary className="button button-secondary button-small">Beoordelen</summary><div className="detail" style={{position:"fixed",inset:"88px 30px 30px auto",width:"min(760px,calc(100vw - 60px))",overflow:"auto",zIndex:15,boxShadow:"0 25px 70px -25px rgba(16,47,69,.45)",border:"1px solid var(--line)",borderRadius:12}}><MatrixDetail projectId={project.id} req={req}/></div></details></td></tr>})}</tbody></table>{filtered.length===0&&<Empty title="Geen eisen gevonden" text="Pas de filters aan of voeg eerst eisen toe."/>}</section></div>;
}

function MatrixDetail({projectId,req}:{projectId:string;req:FullProject["requirements"][number]}){const assessment=req.assessments[0];return <div className="stack"><div><div className="eyebrow">{req.number} · {req.category}</div><h2 style={{marginTop:8}}>{req.title}</h2></div><div><h3>Oorspronkelijke eis</h3><p>{req.originalText}</p><p className="source-quote">{req.sourceFragment}</p><p className="muted" style={{fontSize:11}}>Bronlocatie: {req.sourceDocument?.name||"Handmatig"}, {req.sourceLocation}</p></div><div><h3>Voorgestelde bewijsstukken</h3><div style={{marginTop:10}}>{req.matches.length===0?<p className="notice warning">Er zijn nog geen voorstellen. Genereer voorstellen vanuit de matrix.</p>:req.matches.map(match=><div className="match-card" key={match.id}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><strong>{match.evidenceDocument.title}</strong><span className="score">{match.score}%</span></div><p className="muted" style={{fontSize:12}}>{match.explanation}</p>{match.fragment?<p className="source-quote">{match.fragment}</p>:<p className="notice warning">Geen bronfragment; dit is een zwak voorstel.</p>}<p className="muted" style={{fontSize:10}}>Bron: {match.evidenceDocument.fileName} · {match.sourceLocation}</p>{match.warnings&&<p className="notice warning">{match.warnings}</p>}</div>)}</div></div><form action={saveAssessmentAction.bind(null,projectId,req.id)} className="form-stack"><h3>Menselijke beoordeling</h3><Select name="evidenceMatchId" label="Gekoppeld bewijs" options={req.matches.map(m=>m.id)} optionLabels={Object.fromEntries(req.matches.map(m=>[m.id,`${m.evidenceDocument.title} (${m.score}%)`]))} defaultValue={assessment?.evidenceMatchId||""}/><Select name="status" label="Beoordelingsstatus" options={STATUSES} defaultValue={assessment?.status||req.status}/><div className="field"><label htmlFor={`answer-${req.id}`}>Intern conceptantwoord</label><textarea id={`answer-${req.id}`} name="draftAnswer" defaultValue={assessment?.draftAnswer}/></div><div className="field"><label htmlFor={`notes-${req.id}`}>Opmerkingen</label><textarea id={`notes-${req.id}`} name="notes" defaultValue={assessment?.notes}/></div><div className="grid-2"><Field name="owner" label="Eigenaar" defaultValue={assessment?.owner||""}/><Field name="deadline" label="Deadline" type="date" defaultValue={assessment?.deadline||""}/></div><label className="checkline"><input type="checkbox" name="approved" defaultChecked={assessment?.approved}/> Beslissing gecontroleerd en goedgekeurd</label><SubmitButton pending="Beoordeling opslaan…">Menselijke beoordeling opslaan</SubmitButton></form></div>}

function Tasks({project}:{project:FullProject}){const open=project.tasks.filter(t=>t.status==="open");return <section className="panel"><div className="panel-pad"><h2>Openstaande acties</h2><p className="muted" style={{fontSize:13}}>Taken ontstaan wanneer bij een beoordeling een deadline wordt vastgelegd.</p></div>{open.length===0?<Empty title="Geen openstaande acties" text="Leg in de matrix een eigenaar en deadline vast om een actie te maken."/>:open.map(t=><div className="list-row" key={t.id}><div><h3>{t.title}</h3><p className="muted" style={{fontSize:11}}>{t.requirementId?project.requirements.find(r=>r.id===t.requirementId)?.title:"Algemene actie"}</p></div><span>{t.owner||"Niet toegewezen"}</span><span className="mono">{t.deadline?formatDate(t.deadline):"Geen deadline"}</span></div>)}</section>}
function Audit({project}:{project:FullProject}){return <section className="panel table-wrap"><div className="panel-pad"><h2>Auditlog</h2><p className="muted" style={{fontSize:13}}>Chronologisch spoor van relevante mutaties binnen dit dossier.</p></div><table><thead><tr><th>Datum en tijd</th><th>Actie</th><th>Betrokken object</th><th>Oude waarde</th><th>Nieuwe waarde</th><th>Gebruiker</th></tr></thead><tbody>{project.auditEvents.map(event=><tr key={event.id}><td className="mono">{formatDateTime(event.createdAt)}</td><td>{event.action}</td><td>{event.entity}</td><td className="muted" style={{maxWidth:220,whiteSpace:"pre-wrap"}}>{event.oldValue.slice(0,180)||"—"}</td><td style={{maxWidth:220,whiteSpace:"pre-wrap"}}>{event.newValue.slice(0,180)||"—"}</td><td>{event.user}</td></tr>)}</tbody></table>{project.auditEvents.length===0&&<Empty title="Nog geen gebeurtenissen" text="Wijzigingen verschijnen hier automatisch."/>}</section>}
function Export({project}:{project:FullProject}){return <div className="grid-wide"><section className="panel panel-pad"><h2>Dossier exporteren</h2><p className="muted">Maak een volledige eisen-bewijsmatrix als CSV of open een nette dossierweergave om via de browser als PDF op te slaan.</p><div style={{display:"flex",gap:10,marginTop:22,flexWrap:"wrap"}}><a className="button button-primary" href={`/api/projecten/${project.id}/export.csv`}>CSV-matrix downloaden</a><Link className="button button-secondary" target="_blank" href={`/projecten/${project.id}/dossier`}>Afdrukbaar dossier openen</Link></div></section><aside className="notice warning">Exports kunnen vertrouwelijke informatie bevatten. Controleer ontvangers, classificaties en bronfragmenten voordat u het dossier deelt. {DISCLAIMER}</aside></div>}

function Empty({title,text}:{title:string;text:string}){return <div className="empty"><h3>{title}</h3><p>{text}</p></div>}
function FileField(){return <div className="field"><label htmlFor="file">Bestand *</label><input id="file" name="file" type="file" accept=".pdf,.docx,.txt" required/><small>Toegestaan: PDF, DOCX en TXT. Maximaal 10 MB.</small></div>}
function Field({name,label,type="text",placeholder,defaultValue}:{name:string;label:string;type?:string;placeholder?:string;defaultValue?:string}){return <div className="field"><label htmlFor={name}>{label}</label><input id={name} name={name} type={type} placeholder={placeholder} defaultValue={defaultValue}/></div>}
function Select({name,label,options,defaultValue,optionLabels}:{name:string;label:string;options:string[];defaultValue?:string;optionLabels?:Record<string,string>}){return <div className="field"><label htmlFor={name}>{label}</label><select id={name} name={name} defaultValue={defaultValue}>{name==="evidenceMatchId"&&<option value="">Geen specifiek bewijs gekoppeld</option>}{options.map(o=><option key={o} value={o}>{optionLabels?.[o]||o}</option>)}</select></div>}
function SelectCompact({name,label,options,value,optionLabels}:{name:string;label:string;options:string[];value?:string;optionLabels?:Record<string,string>}){return <div className="field"><label htmlFor={`filter-${name}`}>{label}</label><select id={`filter-${name}`} name={name} defaultValue={value||""}><option value="">Alle</option>{options.map(o=><option key={o} value={o}>{optionLabels?.[o]||o}</option>)}</select></div>}
