import { PrismaClient } from "@prisma/client";
import { LocalEvidenceMatcher } from "../lib/matching";

const db = new PrismaClient();
const reqs = [
  ["E-001","Encryptie van gegevens","De leverancier moet persoonsgegevens tijdens transport en opslag versleutelen met actuele, algemeen aanvaarde cryptografische standaarden.","informatiebeveiliging","§ 4.1"],
  ["E-002","Toegangsbeheer","De opdrachtnemer waarborgt rolgebaseerd toegangsbeheer en voert ieder kwartaal een toegangsreview uit.","informatiebeveiliging","§ 4.2"],
  ["E-003","Controleerbare logging","Het AI-systeem dient beheerdershandelingen en relevante gebruikersacties controleerbaar te loggen.","informatiebeveiliging","§ 4.3"],
  ["E-004","Bewaartermijnen","De inschrijver toont aan dat persoonsgegevens na afloop van de overeengekomen bewaartermijn worden verwijderd.","privacy","§ 5.1"],
  ["E-005","Subverwerkers","De leverancier beschrijft alle subverwerkers, hun locaties en het doel van verwerking.","privacy","§ 5.2"],
  ["E-006","Incidentmelding","Beveiligingsincidenten met mogelijke impact op de opdrachtgever moeten binnen 24 uur worden gemeld.","informatiebeveiliging","§ 4.6"],
  ["E-007","Menselijke tussenkomst","Bij besluiten met aanmerkelijke gevolgen moet betekenisvolle menselijke tussenkomst mogelijk zijn.","AI en algoritmen","§ 6.1"],
  ["E-008","Uitleg algoritmische uitkomsten","De leverancier dient begrijpelijk uit te leggen welke factoren een algoritmische uitkomst hoofdzakelijk bepalen.","AI en algoritmen","§ 6.2"],
  ["E-009","Wijzigingen van het AI-model","De opdrachtgever moet vooraf worden geïnformeerd over materiële wijzigingen van het gebruikte AI-model.","AI en algoritmen","§ 6.4"],
  ["E-010","Continuïteit en herstel","De inschrijver toont aan dat continuïteits- en herstelprocedures minimaal jaarlijks worden getest.","continuïteit","§ 7.1"],
  ["E-011","Opslag binnen de EER","Persoonsgegevens moeten uitsluitend binnen de Europese Economische Ruimte worden opgeslagen.","privacy","§ 5.4"],
];

async function main(){
  await db.project.deleteMany({where:{reference:"WD-2026-041"}});
  const project=await db.project.create({data:{id:"demo-waterdam",name:"AI-planningssoftware Gemeente Waterdam",client:"Gemeente Waterdam",reference:"WD-2026-041",dueDate:new Date("2026-11-16T12:00:00"),product:"Planwijzer AI",productVersion:"2.3",owner:"Eva de Vries",notes:"Fictief demonstratiedossier voor een Europese aanbesteding.",auditEvents:{create:{action:"Demodossier geladen",entity:"Project",newValue:"Synthetische inhoud",user:"Lokale gebruiker"}}}});
  const source=await db.sourceDocument.create({data:{projectId:project.id,name:"Programma van Eisen Waterdam.txt",storedName:"demo-pve.txt",type:"programma van eisen",mimeType:"text/plain",extractedText:reqs.map(r=>`${r[4]} ${r[2]}`).join("\n\n")}});
  const aiSource=await db.sourceDocument.create({data:{projectId:project.id,name:"AI- en privacyvragenlijst Waterdam.txt",storedName:"demo-ai-vragenlijst.txt",type:"AI-vragenlijst",mimeType:"text/plain",extractedText:reqs.slice(3,9).map(r=>`${r[4]} ${r[2]}`).join("\n\n")}});
  for (const [number,title,text,category,location] of reqs) await db.requirement.create({data:{projectId:project.id,sourceDocumentId:["E-004","E-005","E-007","E-008","E-009","E-011"].includes(number)?aiSource.id:source.id,number,title,originalText:text,category,sourceLocation:location,sourceFragment:text,priority:"verplicht",origin:"automatisch"}});
  const evidenceData=[
    {title:"Informatiebeveiligingsbeleid 2026",documentType:"beleidsdocument",description:"Kaders voor encryptie, toegangsbeheer en logging.",organization:"Planwijzer Systemen B.V.",product:"Planwijzer AI",productVersion:"2.3",environment:"productie",owner:"Nora Smit",issuedAt:new Date("2026-02-01"),expiresAt:new Date("2027-02-01"),confidentiality:"intern",tags:"encryptie, toegangsbeheer, logging",fileName:"informatiebeveiligingsbeleid.txt",storedName:"demo-security.txt",mimeType:"text/plain",extractedText:"Gegevens worden tijdens transport beschermd met TLS 1.3 en in opslag met AES-256. Toegang is rolgebaseerd en ieder kwartaal beoordeelt de systeemeigenaar de toegekende rechten. Beheerdershandelingen worden onveranderbaar gelogd en twaalf maanden bewaard."},
    {title:"Subprocessorregister",documentType:"register",description:"Actuele lijst van subverwerkers en verwerkingslocaties.",organization:"Planwijzer Systemen B.V.",product:"Planwijzer AI",productVersion:"2.3",environment:"productie",owner:"Mila van Dijk",issuedAt:new Date("2026-08-12"),expiresAt:null,confidentiality:"vertrouwelijk",tags:"subverwerkers, EER, locaties",fileName:"subprocessorregister.txt",storedName:"demo-subprocessors.txt",mimeType:"text/plain",extractedText:"Rekenwolk Noord B.V. verzorgt hosting in Amsterdam, Nederland. Berichtstroom B.V. verzorgt e-mailaflevering in Frankfurt, Duitsland. Alle productiegegevens worden binnen de EER verwerkt en opgeslagen."},
    {title:"Architectuurbeschrijving Planwijzer AI",documentType:"architectuurdiagram",description:"Technische componenten en gegevensstromen.",organization:"Planwijzer Systemen B.V.",product:"Planwijzer AI",productVersion:"2.2",environment:"productie",owner:"Sven Meijer",issuedAt:new Date("2026-01-18"),expiresAt:null,confidentiality:"vertrouwelijk",tags:"architectuur, encryptie, logging",fileName:"architectuurbeschrijving.txt",storedName:"demo-architecture.txt",mimeType:"text/plain",extractedText:"De applicatie gebruikt een versleutelde database in de regio West-Europa. Auditgebeurtenissen gaan naar een afgescheiden logopslag. Dit document beschrijft versie 2.2 en is nog niet bijgewerkt voor de nieuwe planningsmodule."},
    {title:"Procedure beveiligingsincidenten",documentType:"procedure",description:"Melding, triage en escalatie van incidenten.",organization:"Planwijzer Systemen B.V.",product:"Organisatiebreed",productVersion:"",environment:"productie",owner:"Nora Smit",issuedAt:new Date("2026-04-04"),expiresAt:new Date("2027-04-04"),confidentiality:"intern",tags:"incident, melding, 24 uur",fileName:"incidentprocedure.txt",storedName:"demo-incidents.txt",mimeType:"text/plain",extractedText:"Een incident met mogelijke impact op een opdrachtgever wordt direct geëscaleerd. De contracteigenaar doet uiterlijk binnen 24 uur een eerste melding met aard, impact en genomen maatregelen."},
    {title:"Model card Planwijzer voorspeller",documentType:"technische beschrijving",description:"Doel, beperkingen en uitlegbaarheid van het planningsmodel.",organization:"Planwijzer Systemen B.V.",product:"Planwijzer AI",productVersion:"2.3",environment:"productie",owner:"Ravi de Boer",issuedAt:new Date("2026-07-09"),expiresAt:null,confidentiality:"intern",tags:"AI, model, uitleg, menselijke controle",fileName:"model-card.txt",storedName:"demo-model-card.txt",mimeType:"text/plain",extractedText:"Het model rangschikt planningsopties op reistijd, beschikbaarheid en urgentie. Een planner ziet de drie zwaarst wegende factoren en kan iedere aanbeveling negeren of aanpassen. Besluiten worden nooit zonder bevestiging van een planner uitgevoerd. Wijzigingen worden intern getest."},
    {title:"Continuïteits- en herstelplan",documentType:"procedure",description:"Herstelvolgorde, rollen en testcyclus.",organization:"Planwijzer Systemen B.V.",product:"Planwijzer AI",productVersion:"2.3",environment:"productie",owner:"Iris de Jong",issuedAt:new Date("2026-03-20"),expiresAt:new Date("2027-03-20"),confidentiality:"strikt vertrouwelijk",tags:"continuïteit, herstel, test",fileName:"continuiteitsplan.txt",storedName:"demo-bcp.txt",mimeType:"text/plain",extractedText:"Het herstelplan beschrijft rollen, afhankelijkheden en een herstelvolgorde. Een volledige hersteltest vindt jaarlijks plaats; de laatste oefening was op 14 februari 2026 en is vastgelegd in een afzonderlijk testrapport."},
    {title:"Pentestsamenvatting 2024",documentType:"testresultaat",description:"Samenvatting van een externe penetratietest op een oudere versie.",organization:"Planwijzer Labs B.V.",product:"Planwijzer AI",productVersion:"1.9",environment:"test",owner:"Nora Smit",issuedAt:new Date("2024-05-10"),expiresAt:new Date("2025-05-10"),confidentiality:"vertrouwelijk",tags:"pentest, beveiliging",fileName:"pentest-samenvatting.txt",storedName:"demo-pentest.txt",mimeType:"text/plain",extractedText:"De testomgeving van versie 1.9 is onderzocht op veelvoorkomende kwetsbaarheden. Twee bevindingen met gemiddeld risico zijn na afloop hertest."},
  ];
  for (const item of evidenceData) await db.evidenceDocument.create({data:{projectId:project.id,...item}});
  const loaded=await db.project.findUniqueOrThrow({where:{id:project.id},include:{requirements:true,evidenceDocuments:true}}); const matcher=new LocalEvidenceMatcher();
  for(const req of loaded.requirements) for(const m of await matcher.match(req,loaded.evidenceDocuments,loaded)) await db.evidenceMatch.create({data:{requirementId:req.id,...m}});
  const statuses:Record<string,string>={"E-001":"voldoende onderbouwd","E-002":"gedeeltelijk onderbouwd","E-003":"mogelijk passend","E-004":"ontbrekend bewijs","E-005":"voldoende onderbouwd","E-006":"voldoende onderbouwd","E-007":"gedeeltelijk onderbouwd","E-008":"gedeeltelijk onderbouwd","E-009":"onvoldoende onderbouwd","E-010":"voldoende onderbouwd","E-011":"onvoldoende onderbouwd"};
  for(const req of loaded.requirements){const status=statuses[req.number];await db.requirement.update({where:{id:req.id},data:{status}});await db.assessment.create({data:{requirementId:req.id,status,draftAnswer:status==="ontbrekend bewijs"?"Nog op te stellen antwoord.":"Zie gekoppelde bewijsstukken en bronfragmenten.",notes:["E-004","E-009","E-011"].includes(req.number)?"Aanvullend, scopespecifiek bewijs opvragen.":"Menselijk gecontroleerd in de demo.",owner:req.category==="privacy"?"Mila van Dijk":req.category==="AI en algoritmen"?"Ravi de Boer":"Nora Smit",deadline:["E-004","E-009","E-011"].includes(req.number)?new Date("2026-10-15"):null,approved:status==="voldoende onderbouwd"}})}
  console.log(`Demo geladen: ${project.name}`);
}
main().finally(()=>db.$disconnect());
