import Link from "next/link";
import { ArrowUpRight, CheckCircle, FileText, MagnifyingGlass, ShieldCheck, Warning } from "@phosphor-icons/react/dist/ssr";
import { PRODUCT } from "@/lib/config/product";

export default function LandingPage() {
  return <main className="landing-page">
    <section className="landing-shell landing-hero"><div className="landing-hero-copy"><div className="eyebrow">Bewijsdossiers voor IT- en AI-leveranciers</div><h1>Maak van bewijs een herbruikbare voorsprong.</h1><p className="landing-lead">{PRODUCT.name} brengt aanbestedingseisen, bewijsstukken en menselijke beoordeling samen in één dossier dat uw team kan controleren, hergebruiken en delen.</p><div className="landing-actions"><Link href="/demo" className="button button-primary">Start interactieve demo <ArrowUpRight size={18} weight="bold" /></Link><Link href="/pitch" className="button button-secondary">Voor investeerders</Link></div><div className="landing-meta"><span className="pulse-dot" /> Lokale MVP · Nederlandse workflow · menselijke beslissing</div></div><div className="landing-visual" aria-label="Voorbeeld van een eisen-bewijsmatrix"><div className="visual-topline"><span><span className="visual-dot" /> DEMO-WATERDAM</span><span className="mono">EISEN-BEWIJSMATRIX</span></div><div className="visual-context"><div><span className="visual-kicker">Actief dossier</span><strong>AI-planningssoftware</strong><small>Gemeente Waterdam · WD-2026-041</small></div><span className="visual-progress">91%</span></div><div className="visual-stats"><span><b>11</b><small>eisen</small></span><span><b>7</b><small>bewijsstukken</small></span><span><b>3</b><small>hiaten</small></span></div><div className="visual-rows"><div className="visual-row"><span className="mono">E-001</span><strong>Encryptie van gegevens</strong><span className="visual-status good"><CheckCircle size={14} /> voldoende</span></div><div className="visual-row"><span className="mono">E-005</span><strong>Subverwerkers</strong><span className="visual-status review"><MagnifyingGlass size={14} /> voorstel</span></div><div className="visual-row"><span className="mono">E-009</span><strong>Wijziging AI-model</strong><span className="visual-status missing"><Warning size={14} /> hiaat</span></div></div><div className="visual-foot"><ShieldCheck size={15} /> Bronfragmenten blijven zichtbaar · beoordeling blijft menselijk</div></div></section>
    <section className="landing-shell landing-thesis" id="product"><div className="section-index">01 / Waarom {PRODUCT.name}</div><div className="thesis-copy"><h2>Dezelfde antwoorden. Iedere keer opnieuw gezocht.</h2><p>Een securityvragenlijst, aanbesteding of AI-uitvraag vraagt vaak om vergelijkbaar bewijs. Vandaag zit dat bewijs verspreid over policies, auditrapporten, model cards en spreadsheets.</p><div className="thesis-flow"><span>Uitvraag</span><b>→</b><span>Bewijs zoeken</span><b>→</b><span>Scope controleren</span><b>→</b><span>Dossier delen</span></div></div></section>
    <section className="landing-shell landing-workflow" id="werkwijze"><div className="section-index">02 / Werkwijze</div><div className="workflow-content"><h2>Van bronfragment naar onderbouwde beslissing.</h2><div className="workflow-grid"><article><span className="workflow-number">01</span><FileText size={24} /><h3>Leg de uitvraag vast</h3><p>Upload PDF, DOCX of TXT. Eisen blijven gekoppeld aan document, pagina of alinea.</p></article><article><span className="workflow-number">02</span><MagnifyingGlass size={24} /><h3>Vind mogelijke matches</h3><p>Lokale matching toont relevante bewijsstukken, fragmenten, scores en scopewaarschuwingen.</p></article><article><span className="workflow-number">03</span><CheckCircle size={24} /><h3>Laat de mens beslissen</h3><p>De eigenaar beoordeelt, schrijft een intern antwoord en legt deadline en auditspoor vast.</p></article></div></div></section>
    <section className="landing-shell landing-proof" id="vertrouwen"><div className="proof-panel"><div><div className="eyebrow">Transparant vanaf dag één</div><h2>Geen automatische certificering. Wel aantoonbaar beter voorbereid.</h2><p>Een voorgestelde koppeling is geen juridisch oordeel, certificering of garantie van naleving. IPC maakt zichtbaar wat de bron zegt, welk bewijs er ligt en welke menselijke beslissing nog nodig is.</p></div><div className="proof-list"><span><ShieldCheck size={19} /> Bronfragment bij iedere suggestie</span><span><CheckCircle size={19} /> Menselijke status als enige voortgang</span><span><Warning size={19} /> Openstaande hiaten blijven zichtbaar</span></div></div></section>
    <section className="landing-shell landing-cta"><div><div className="eyebrow">Klaar om te kijken?</div><h2>Open het Waterdam-dossier en volg één eis helemaal.</h2></div><div><p>De demo gebruikt synthetische Nederlandse gegevens en is direct lokaal beschikbaar.</p><Link href="/demo" className="button button-primary">Naar de demo <ArrowUpRight size={18} weight="bold" /></Link></div></section>
    <div className="landing-shell landing-disclaimer">{PRODUCT.disclaimer} De applicatie ondersteunt de voorbereiding en beoordeling van bewijsdossiers. De applicatie geeft geen juridisch oordeel, certificering of garantie van naleving.</div>
  </main>;
}
